#yaml:
#YAML은 계층 적 구성 데이터를 지정하기위한 조금 더 편리한 형식이다.
#반복되는 key 접두사가 제거되고 계층적인 구조가 명확히 드러난다.
#YAML은 닷(.)과 인덴트로 계층을 구분하고 있다. 계층 구조에서 인덴트가 조금이라도 잘못되거나 벗어나면 값을 못읽거나 오류를 발생시키기에 인덴트에 주의.
#yml은 작성 순서가 우선 순위의 영향을 받는다.
#스프링 버전과 관계없이 YAML은 한 파일에서 다중 Profile를 정의할 수 있다.
#'---' 로 Profile을 구별한다.

#8080 포트가 사용중이어서 포트를 9502로 변경함.
server:
  port: 9502

#datasource : 연결할 Database 설정 (url, driver, username, password)
spring:
  datasource:
    url: jdbc:mariadb://59.1.39.122:1577/anydesk_address
    username: sogno
    password: sogno1234
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

  devtools:
    livereload:
      enabled: true

  thymeleaf3:
    decoupled-logic: true
